Fix failed UDF query
Before now, using a UDF in a query threw this error;

File \"/osprey/osprey_worker/src/osprey/engine/query_language/ast_druid_translator.py\", line 102, in transform_Call
     udf, _ = self._udf_node_mapping[id(node)]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 139836295173120"}

This happened because all the validators weren't being run during a
query, for some reason the REGISTRY didn't load all, just the additional
ones that are needed for a query.

DidAddLabel was also affected by this, this also fixes that.

I've also modified RegexMatch to use the right arguments as used in the
docs, item and regex created confusion as the docs stated target and
pattern, and using that in the query threw an error.

Signed-off-by: Chihurumnaya Ibiam <ibiamchihurumnaya@gmail.com>